#!/usr/bin/env bash
# build-single.sh — Bundle vm-init into a single self-contained shell script.
#
# Concatenates modules/_common.sh, all modules/*.sh, vm-init.sh, and the
# default vm-init.yml into one file: dist/vm-init-<version>.
#
# The resulting script can be downloaded and run directly (no tarball, no
# repo checkout). It sets VM_INIT_BUNDLED=1 so the orchestrator skips its
# per-module `source` calls and uses the inlined copies instead. The default
# config is embedded via an `_emit_default_config` heredoc, which the
# orchestrator materializes to a tempfile when the user does not pass
# --config and no on-disk default exists.
#
# Usage: scripts/build-single.sh [output_dir]
#   output_dir defaults to <repo>/dist

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

OUTPUT_DIR="${1:-${REPO_ROOT}/dist}"

if [[ -f "${REPO_ROOT}/VERSION" ]]; then
  VERSION=$(tr -d '[:space:]' < "${REPO_ROOT}/VERSION")
else
  VERSION="0.0.0-dev"
fi

NAME="vm-init"
OUTPUT_PATH="${OUTPUT_DIR}/${NAME}-${VERSION}"

COMMON_SH="${REPO_ROOT}/modules/_common.sh"
ORCHESTRATOR="${REPO_ROOT}/vm-init.sh"
DEFAULT_YML="${REPO_ROOT}/vm-init.yml"
MODULES=(
  "${REPO_ROOT}/modules/apt.sh"
  "${REPO_ROOT}/modules/ufw.sh"
  "${REPO_ROOT}/modules/fail2ban.sh"
  "${REPO_ROOT}/modules/dns.sh"
  "${REPO_ROOT}/modules/docker.sh"
  "${REPO_ROOT}/modules/python.sh"
  "${REPO_ROOT}/modules/github-tools.sh"
  "${REPO_ROOT}/modules/github-releases.sh"
  "${REPO_ROOT}/modules/shell.sh"
)

for f in "$COMMON_SH" "$ORCHESTRATOR" "$DEFAULT_YML" "${MODULES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "build-single: missing source file: $f" >&2
    exit 1
  fi
done

# The default YAML is embedded verbatim inside a single-quoted heredoc, so
# user content like $(...) won't be interpreted. Defend against the
# (unlikely) case where the YAML contains the end-of-heredoc sentinel.
if grep -q '__VM_INIT_DEFAULT_YAML__' "$DEFAULT_YML"; then
  echo "build-single: vm-init.yml contains the reserved heredoc sentinel" >&2
  echo "  (__VM_INIT_DEFAULT_YAML__). Rename that string before building." >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

strip_shebang() {
  # Drop a leading #! line if present; everything else passes through.
  awk 'NR==1 && /^#!/ { next } { print }' "$1"
}

section_header() {
  printf '\n# %s\n# %s\n# %s\n\n' \
    '==========================================================================' \
    ">>> $1" \
    '=========================================================================='
}

TMP_OUT="${OUTPUT_PATH}.tmp"
trap 'rm -f "$TMP_OUT"' EXIT

{
  cat <<HEADER
#!/usr/bin/env bash
# vm-init — single-file bundle (generated by scripts/build-single.sh).
#
# This file bundles modules/_common.sh, all modules/*.sh, the orchestrator
# vm-init.sh, and the default vm-init.yml into one self-contained script.
# Do not edit by hand — changes here will be lost on the next build.
#
# Version:    ${VERSION}
# Generated:  $(date -u +%Y-%m-%dT%H:%M:%SZ)

set -euo pipefail

export VM_INIT_BUNDLED=1
export VM_INIT_BUNDLED_VERSION="${VERSION}"
HEADER

  section_header "modules/_common.sh"
  strip_shebang "$COMMON_SH"

  section_header "embedded default vm-init.yml"
  cat <<'EMIT_FN_OPEN'
_emit_default_config() {
  cat <<'__VM_INIT_DEFAULT_YAML__'
EMIT_FN_OPEN
  cat "$DEFAULT_YML"
  cat <<'EMIT_FN_CLOSE'
__VM_INIT_DEFAULT_YAML__
}
EMIT_FN_CLOSE

  for m in "${MODULES[@]}"; do
    section_header "modules/$(basename "$m")"
    strip_shebang "$m"
  done

  section_header "vm-init.sh (orchestrator)"
  strip_shebang "$ORCHESTRATOR"
} > "$TMP_OUT"

if ! bash -n "$TMP_OUT"; then
  echo "build-single: generated script failed syntax check" >&2
  exit 1
fi

mv "$TMP_OUT" "$OUTPUT_PATH"
trap - EXIT
chmod +x "$OUTPUT_PATH"

if command -v sha256sum >/dev/null 2>&1; then
  (cd "$OUTPUT_DIR" && sha256sum "$(basename "$OUTPUT_PATH")") > "${OUTPUT_PATH}.sha256"
else
  (cd "$OUTPUT_DIR" && shasum -a 256 "$(basename "$OUTPUT_PATH")") > "${OUTPUT_PATH}.sha256"
fi

size_bytes=$(wc -c < "$OUTPUT_PATH" | tr -d '[:space:]')
size_kib=$(( (size_bytes + 512) / 1024 ))
line_count=$(wc -l < "$OUTPUT_PATH" | tr -d '[:space:]')

echo ""
echo "Built: ${OUTPUT_PATH}"
echo "Size:  ${size_bytes} bytes (~${size_kib} KiB, ${line_count} lines)"
echo "SHA:   $(cat "${OUTPUT_PATH}.sha256")"
echo ""
echo "To run locally:"
echo "  sudo ${OUTPUT_PATH} --dry-run"
echo ""
echo "To install on a target machine:"
echo "  curl -fsSL <url>/${NAME}-${VERSION} -o /usr/local/sbin/vm-init"
echo "  sudo chmod +x /usr/local/sbin/vm-init"
echo "  sudo vm-init --dry-run                # uses embedded default"
echo "  sudo vm-init"
echo ""
echo "To customize the config before running:"
echo "  vm-init --write-default-config        # writes ./vm-init.yml (no sudo)"
echo "  \$EDITOR vm-init.yml"
echo "  sudo vm-init --config \"\$(pwd)/vm-init.yml\""
